name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TESTCONTAINERS_RYUK_DISABLED: true
      TESTCONTAINERS_CHECKS_DISABLE: true
      TESTCONTAINERS_DOCKER_IMAGE_OVERRIDE: mongo:7.0.5

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Set up JDK 21 with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          cache-dependency-path: ProductService/productservice/pom.xml

      - name: Verify Docker
        run: |
          docker --version
          docker info
          docker run --rm hello-world
      
      - name: Build and Run Tests
        run: |
          cd ProductService/productservice
          ./mvnw -B clean verify -Dsurefire.forkCount=1 -Dsurefire.reuseForks=true
